version: '3'

services:

  tp1_www:
    build: ./
    restart: always
    ports:
      - 8086:80
    extra_hosts:
      - "tp1.local:10.6.0.2"
    hostname: tp1.local
    domainname: local
    environment:
      ITDEE_DB_HOST: tp1_db
      ITDEE_DB_PORT: 5432
      ITDEE_DB_USER: user
      ITDEE_DB_PASSWORD: TPass352
      ITDEE_DB_NAME: airport
    networks:
      tp1net:
        ipv4_address: 10.6.0.2
    volumes:
      - ./docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/var/www/html
    links:
      - tp1_db:tp1_db
    expose:
      - 9003
      - 9000
      - 80

  tp1_db:
    image: postgres:latest
    restart: always
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: airport
      POSTGRES_USER: user
      POSTGRES_PASSWORD: TPass352
      POSTGRES_ROOT_PASSWORD: RPass352
    volumes:
      - ./docker/postgres:/var/lib/postgres
    networks:
      tp1net:
        ipv4_address: 10.6.0.3
    expose:
      - 5432

  tp1_rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5676:5672
      - 15676:15672
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: user
    networks:
      tp1net:
        ipv4_address: 10.6.0.4
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - rabbit-log:/var/log/rabbitmq

volumes:
  rabbit-data:
  rabbit-log:
networks:
  tp1net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1